--- 
#
# This is a GemInstaller config file (http://geminstaller.rubyforge.org)
#
# This is a list of all gems needed to work with watircuke
#
defaults:
  install_options: --include-dependencies
gems: 
- name: cucumber
- name: watir
- name: firewatir
- name: rb-appscript
- name: safariwatir
- name: syntax
- name: colorize
- name: chronic                                                       
